"""initial hiring schema

Revision ID: 713d13d9e9c1
Revises:
Created: 2026-09-04 16:43:37.741311+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "713d13d9e9c1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("description_raw", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("voice_persona", sa.String(length=32), nullable=False),
        sa.Column("persona_name", sa.String(length=64), nullable=True),
        sa.Column("from_phone_number", sa.String(length=20), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("hunar_agent_id", sa.Uuid(), nullable=True),
        sa.Column("hunar_agent_code", sa.String(length=64), nullable=True),
        sa.Column("agent_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("agent_prompt", sa.Text(), nullable=True),
        sa.Column("objective", sa.Text(), nullable=True),
        sa.Column("introduction", sa.Text(), nullable=True),
        sa.Column("result_prompt", sa.Text(), nullable=True),
        sa.Column(
            "result_schema",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "field_spec",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job")),
    )
    op.create_index(op.f("ix_job_hunar_agent_id"), "job", ["hunar_agent_id"], unique=False)
    op.create_index(op.f("ix_job_status"), "job", ["status"], unique=False)
    op.create_table(
        "candidate",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("mobile_number", sa.String(length=20), nullable=False),
        sa.Column("raw_mobile", sa.String(length=40), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column(
            "extra",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["job.id"], name=op.f("fk_candidate_job_id_job"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate")),
        sa.UniqueConstraint("job_id", "mobile_number", name="candidate_per_job"),
    )
    op.create_index(op.f("ix_candidate_decision"), "candidate", ["decision"], unique=False)
    op.create_index(op.f("ix_candidate_job_id"), "candidate", ["job_id"], unique=False)
    op.create_table(
        "screening_question",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("field_key", sa.String(length=64), nullable=False),
        sa.Column("answer_type", sa.String(length=16), nullable=False),
        sa.Column(
            "enum_options",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("extraction_hint", sa.Text(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("is_knockout", sa.Boolean(), nullable=False),
        sa.Column(
            "scoring_rule",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
            name=op.f("fk_screening_question_job_id_job"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_screening_question")),
        sa.UniqueConstraint("job_id", "field_key", name="field_key_per_job"),
    )
    op.create_index(
        op.f("ix_screening_question_job_id"), "screening_question", ["job_id"], unique=False
    )
    op.create_index(
        "ix_screening_question_order", "screening_question", ["job_id", "order_index"], unique=False
    )
    op.create_table(
        "call_attempt",
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("candidate_id", sa.Uuid(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("callback_token", sa.String(length=64), nullable=False),
        sa.Column("hunar_call_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=32), nullable=False),
        sa.Column("engagement_status", sa.String(length=32), nullable=True),
        sa.Column("answered_by", sa.String(length=32), nullable=True),
        sa.Column("call_ended_by", sa.String(length=32), nullable=True),
        sa.Column("submit_state", sa.String(length=16), nullable=False),
        sa.Column("recording_url", sa.Text(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("user_speech_duration", sa.Float(), nullable=True),
        sa.Column(
            "raw_result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "normalized_result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column(
            "score_breakdown",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("disqualified", sa.Boolean(), nullable=False),
        sa.Column("disqualified_reason", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("candidate_id IS NOT NULL", name=op.f("ck_call_attempt_one_subject")),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidate.id"],
            name=op.f("fk_call_attempt_candidate_id_candidate"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["job.id"], name=op.f("fk_call_attempt_job_id_job"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_call_attempt")),
        sa.UniqueConstraint("callback_token", name=op.f("uq_call_attempt_callback_token")),
        sa.UniqueConstraint("request_id", name=op.f("uq_call_attempt_request_id")),
    )
    op.create_index(
        op.f("ix_call_attempt_candidate_id"), "call_attempt", ["candidate_id"], unique=False
    )
    op.create_index(
        op.f("ix_call_attempt_hunar_call_id"), "call_attempt", ["hunar_call_id"], unique=True
    )
    op.create_index(op.f("ix_call_attempt_job_id"), "call_attempt", ["job_id"], unique=False)
    op.create_index(
        "ix_call_attempt_job_status", "call_attempt", ["job_id", "status"], unique=False
    )
    op.create_index(
        "ix_call_attempt_sync", "call_attempt", ["status", "last_synced_at"], unique=False
    )
    op.create_table(
        "webhook_event",
        sa.Column("dedupe_key", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("callback_token", sa.String(length=64), nullable=False),
        sa.Column("call_attempt_id", sa.Uuid(), nullable=True),
        sa.Column("signature_valid", sa.Boolean(), nullable=False),
        sa.Column("hunar_timestamp", sa.Integer(), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("process_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_attempt_id"],
            ["call_attempt.id"],
            name=op.f("fk_webhook_event_call_attempt_id_call_attempt"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_event")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_webhook_event_dedupe_key")),
    )
    op.create_index(
        op.f("ix_webhook_event_call_attempt_id"), "webhook_event", ["call_attempt_id"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_event_callback_token"), "webhook_event", ["callback_token"], unique=False
    )
    op.create_index(
        "ix_webhook_event_token", "webhook_event", ["callback_token", "event_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_webhook_event_token", table_name="webhook_event")
    op.drop_index(op.f("ix_webhook_event_callback_token"), table_name="webhook_event")
    op.drop_index(op.f("ix_webhook_event_call_attempt_id"), table_name="webhook_event")
    op.drop_table("webhook_event")
    op.drop_index("ix_call_attempt_sync", table_name="call_attempt")
    op.drop_index("ix_call_attempt_job_status", table_name="call_attempt")
    op.drop_index(op.f("ix_call_attempt_job_id"), table_name="call_attempt")
    op.drop_index(op.f("ix_call_attempt_hunar_call_id"), table_name="call_attempt")
    op.drop_index(op.f("ix_call_attempt_candidate_id"), table_name="call_attempt")
    op.drop_table("call_attempt")
    op.drop_index("ix_screening_question_order", table_name="screening_question")
    op.drop_index(op.f("ix_screening_question_job_id"), table_name="screening_question")
    op.drop_table("screening_question")
    op.drop_index(op.f("ix_candidate_job_id"), table_name="candidate")
    op.drop_index(op.f("ix_candidate_decision"), table_name="candidate")
    op.drop_table("candidate")
    op.drop_index(op.f("ix_job_status"), table_name="job")
    op.drop_index(op.f("ix_job_hunar_agent_id"), table_name="job")
    op.drop_table("job")
    # ### end Alembic commands ###
