"""job agent fingerprint

Revision ID: 89142a6599d9
Revises: 017d87061940
Created: 2026-09-07 08:44:48.180213+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "89142a6599d9"
down_revision: str | None = "017d87061940"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job", sa.Column("agent_fingerprint", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job", "agent_fingerprint")
    # ### end Alembic commands ###
