"""Sourcing schema: prospects, consent and outreach.

Also widens ``call_attempt`` so one table serves both applications. The
check constraint moves from "a call must have a candidate" to "a call has
exactly one subject, a candidate or an outreach target". Alembic does not
autogenerate check-constraint changes, so that part is written by hand;
without it the old constraint would reject every outreach call at insert.

Revision ID: 017d87061940
Revises: 713d13d9e9c1
Created: 2026-09-06 16:49:42.971834+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "017d87061940"
down_revision: str | None = "713d13d9e9c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_allowlist",
        sa.Column("e164", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("consent_source", sa.String(length=64), nullable=False),
        sa.Column("consented_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_allowlist")),
        sa.UniqueConstraint("e164", name=op.f("uq_contact_allowlist_e164")),
    )
    op.create_table(
        "dnc_number",
        sa.Column("e164_sha256", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("e164_sha256", name=op.f("pk_dnc_number")),
    )
    op.create_table(
        "people_search",
        sa.Column("jd_text", sa.Text(), nullable=False),
        sa.Column("jd_sha256", sa.String(length=64), nullable=False),
        sa.Column("extraction_method", sa.String(length=16), nullable=False),
        sa.Column(
            "filters_resolved",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("filters_edited", sa.Boolean(), nullable=False),
        sa.Column("provider", sa.String(length=24), nullable=False),
        sa.Column(
            "provider_query",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("provider_degraded_to", sa.String(length=24), nullable=True),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("credits_charged", sa.Integer(), nullable=False),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_people_search")),
    )
    op.create_index(
        op.f("ix_people_search_jd_sha256"), "people_search", ["jd_sha256"], unique=False
    )
    op.create_table(
        "prospect",
        sa.Column("dedupe_key", sa.String(length=128), nullable=False),
        sa.Column("dedupe_confidence", sa.String(length=8), nullable=False),
        sa.Column("provider", sa.String(length=24), nullable=False),
        sa.Column("provider_person_id", sa.String(length=128), nullable=True),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("headline", sa.Text(), nullable=True),
        sa.Column("job_title", sa.String(length=200), nullable=True),
        sa.Column("seniority", sa.String(length=32), nullable=True),
        sa.Column("company_name", sa.String(length=200), nullable=True),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("years_experience", sa.Integer(), nullable=True),
        sa.Column(
            "skills",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("location_city", sa.String(length=120), nullable=True),
        sa.Column("location_country", sa.String(length=120), nullable=True),
        sa.Column("linkedin_url", sa.Text(), nullable=True),
        sa.Column("phone_status", sa.String(length=16), nullable=False),
        sa.Column("phone_e164", sa.String(length=20), nullable=True),
        sa.Column("do_not_contact", sa.Boolean(), nullable=False),
        sa.Column("fit_score", sa.Integer(), nullable=True),
        sa.Column(
            "fit_reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "raw",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "redacted_fields",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prospect")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_prospect_dedupe_key")),
    )
    op.create_index(op.f("ix_prospect_phone_status"), "prospect", ["phone_status"], unique=False)
    op.create_index("ix_prospect_score", "prospect", ["fit_score"], unique=False)
    op.create_table(
        "outreach_campaign",
        sa.Column("search_id", sa.Uuid(), nullable=True),
        sa.Column("job_title", sa.String(length=200), nullable=False),
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.Column("job_city", sa.String(length=120), nullable=True),
        sa.Column("work_mode", sa.String(length=32), nullable=True),
        sa.Column("role_pitch", sa.Text(), nullable=False),
        sa.Column("comp_range_text", sa.String(length=120), nullable=True),
        sa.Column("recruiter_name", sa.String(length=120), nullable=False),
        sa.Column("hunar_agent_id", sa.Uuid(), nullable=True),
        sa.Column(
            "result_schema",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "field_spec",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("launched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["search_id"],
            ["people_search.id"],
            name=op.f("fk_outreach_campaign_search_id_people_search"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach_campaign")),
    )
    op.create_index(
        op.f("ix_outreach_campaign_status"), "outreach_campaign", ["status"], unique=False
    )
    op.create_table(
        "prospect_search_hit",
        sa.Column("search_id", sa.Uuid(), nullable=False),
        sa.Column("prospect_id", sa.Uuid(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["prospect_id"],
            ["prospect.id"],
            name=op.f("fk_prospect_search_hit_prospect_id_prospect"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["search_id"],
            ["people_search.id"],
            name=op.f("fk_prospect_search_hit_search_id_people_search"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prospect_search_hit")),
        sa.UniqueConstraint("search_id", "prospect_id", name="hit_once"),
    )
    op.create_index(
        op.f("ix_prospect_search_hit_prospect_id"),
        "prospect_search_hit",
        ["prospect_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prospect_search_hit_search_id"), "prospect_search_hit", ["search_id"], unique=False
    )
    op.create_table(
        "outreach_target",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("prospect_id", sa.Uuid(), nullable=False),
        sa.Column("allowlist_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("block_reason", sa.Text(), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["allowlist_id"],
            ["contact_allowlist.id"],
            name=op.f("fk_outreach_target_allowlist_id_contact_allowlist"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["outreach_campaign.id"],
            name=op.f("fk_outreach_target_campaign_id_outreach_campaign"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["prospect_id"],
            ["prospect.id"],
            name=op.f("fk_outreach_target_prospect_id_prospect"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach_target")),
        sa.UniqueConstraint("campaign_id", "prospect_id", name="target_once"),
    )
    op.create_index(
        op.f("ix_outreach_target_campaign_id"), "outreach_target", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_outreach_target_prospect_id"), "outreach_target", ["prospect_id"], unique=False
    )
    op.create_index(op.f("ix_outreach_target_status"), "outreach_target", ["status"], unique=False)
    op.add_column("call_attempt", sa.Column("campaign_id", sa.Uuid(), nullable=True))
    op.add_column("call_attempt", sa.Column("outreach_target_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_call_attempt_campaign_id"), "call_attempt", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_call_attempt_outreach_target_id"),
        "call_attempt",
        ["outreach_target_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_call_attempt_campaign_id_outreach_campaign"),
        "call_attempt",
        "outreach_campaign",
        ["campaign_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_call_attempt_outreach_target_id_outreach_target"),
        "call_attempt",
        "outreach_target",
        ["outreach_target_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###

    # Hand-written: Alembic does not diff check constraints. A call now
    # belongs to exactly one subject, so the constraint becomes an
    # exclusive-or. This is what makes "a call always has a subject, and
    # never two" a guarantee rather than a convention the services are
    # trusted to keep.
    op.drop_constraint(op.f("ck_call_attempt_one_subject"), "call_attempt", type_="check")
    op.create_check_constraint(
        op.f("ck_call_attempt_one_subject"),
        "call_attempt",
        "(candidate_id IS NOT NULL) <> (outreach_target_id IS NOT NULL)",
    )


def downgrade() -> None:
    # Restore the narrower constraint before dropping the column it
    # references, or the drop leaves a constraint pointing at nothing.
    op.drop_constraint(op.f("ck_call_attempt_one_subject"), "call_attempt", type_="check")
    op.create_check_constraint(
        op.f("ck_call_attempt_one_subject"), "call_attempt", "candidate_id IS NOT NULL"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_call_attempt_outreach_target_id_outreach_target"),
        "call_attempt",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_call_attempt_campaign_id_outreach_campaign"), "call_attempt", type_="foreignkey"
    )
    op.drop_index(op.f("ix_call_attempt_outreach_target_id"), table_name="call_attempt")
    op.drop_index(op.f("ix_call_attempt_campaign_id"), table_name="call_attempt")
    op.drop_column("call_attempt", "outreach_target_id")
    op.drop_column("call_attempt", "campaign_id")
    op.drop_index(op.f("ix_outreach_target_status"), table_name="outreach_target")
    op.drop_index(op.f("ix_outreach_target_prospect_id"), table_name="outreach_target")
    op.drop_index(op.f("ix_outreach_target_campaign_id"), table_name="outreach_target")
    op.drop_table("outreach_target")
    op.drop_index(op.f("ix_prospect_search_hit_search_id"), table_name="prospect_search_hit")
    op.drop_index(op.f("ix_prospect_search_hit_prospect_id"), table_name="prospect_search_hit")
    op.drop_table("prospect_search_hit")
    op.drop_index(op.f("ix_outreach_campaign_status"), table_name="outreach_campaign")
    op.drop_table("outreach_campaign")
    op.drop_index("ix_prospect_score", table_name="prospect")
    op.drop_index(op.f("ix_prospect_phone_status"), table_name="prospect")
    op.drop_table("prospect")
    op.drop_index(op.f("ix_people_search_jd_sha256"), table_name="people_search")
    op.drop_table("people_search")
    op.drop_table("dnc_number")
    op.drop_table("contact_allowlist")
    # ### end Alembic commands ###
