"""Database models shared by both application domains.

``CallAttempt`` and ``WebhookEvent`` live here rather than inside
``hiring`` because the sourcing app places calls through exactly the same
machinery. Sharing them means the webhook receiver, the reconciler and
the result normaliser are written once and neither domain needs to know
the other exists.

A call belongs to *either* a screened candidate or an outreach target,
never both. That is expressed as two nullable foreign keys plus a check
constraint rather than a polymorphic subject pair, because Postgres can
enforce the former and cannot enforce the latter.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from typing import Any

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.db import Base, JSONVariant

__all__ = ["CallAttempt", "TimestampMixin", "UUIDMixin", "WebhookEvent"]


class UUIDMixin:
    """Primary key generated by the application, not the database.

    Generating client-side means a row's id is known before it is
    inserted, which lets a call's correlation token and its callback URLs
    be built in one pass rather than requiring a round trip first.
    """

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)


def _utcnow() -> datetime:
    return datetime.now(UTC)


class TimestampMixin:
    """Creation and update timestamps.

    Each column carries both a Python-side and a server-side default. The
    server default keeps rows written outside the ORM honest; the Python
    default means the value is populated in memory immediately after a
    flush. Without the latter, serialising a freshly created row triggers
    a lazy refresh, which raises ``MissingGreenlet`` under async
    SQLAlchemy rather than quietly issuing a query.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow, server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=_utcnow,
        onupdate=_utcnow,
        server_default=func.now(),
        nullable=False,
    )


class CallAttempt(UUIDMixin, TimestampMixin, Base):
    """One attempt to reach one person by voice.

    The two identifiers deserve explanation because they solve different
    problems:

    * ``request_id`` is ours, sent to Hunar and echoed back on the call
      object. Since ``GET /calls/`` cannot be filtered by it, the
      reconciler uses it to match calls it finds while paging, which is
      how a submission that timed out is eventually resolved.
    * ``callback_token`` is an unguessable value embedded in the webhook
      URL path. It exists because the ``call_result_done`` payload
      carries no call identifier at all, so correlation cannot come from
      the body. Putting it in the URL also hardens the other three events
      against payload changes.
    """

    __tablename__ = "call_attempt"
    __table_args__ = (
        CheckConstraint(
            "(candidate_id IS NOT NULL) <> (outreach_target_id IS NOT NULL)",
            name="one_subject",
        ),
        Index("ix_call_attempt_job_status", "job_id", "status"),
        Index("ix_call_attempt_sync", "status", "last_synced_at"),
    )

    # ── subject ──────────────────────────────────────────────
    # A call belongs to exactly one of these, never both and never
    # neither. Two nullable keys with an exclusive-or constraint say that
    # in a way Postgres can enforce; a polymorphic subject pair would
    # leave it to be enforced by whichever service happened to remember.
    job_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("job.id", ondelete="CASCADE"), nullable=True, index=True
    )
    candidate_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("candidate.id", ondelete="CASCADE"), nullable=True, index=True
    )

    campaign_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("outreach_campaign.id", ondelete="CASCADE"), nullable=True, index=True
    )
    outreach_target_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("outreach_target.id", ondelete="CASCADE"), nullable=True, index=True
    )

    # ── correlation ──────────────────────────────────────────
    request_id: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    callback_token: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    hunar_call_id: Mapped[uuid.UUID | None] = mapped_column(unique=True, nullable=True, index=True)

    # ── state ────────────────────────────────────────────────
    status: Mapped[str] = mapped_column(String(32), default="NOT_STARTED", nullable=False)
    lifecycle_status: Mapped[str] = mapped_column(String(32), default="PENDING")
    engagement_status: Mapped[str | None] = mapped_column(String(32), nullable=True)
    answered_by: Mapped[str | None] = mapped_column(String(32), nullable=True)
    call_ended_by: Mapped[str | None] = mapped_column(String(32), nullable=True)

    #: Whether the POST that creates the call actually reached Hunar.
    #: ``UNKNOWN`` means it timed out and may or may not have dialled; the
    #: reconciler resolves it. It is never blindly retried, because a
    #: duplicate is a second real phone call to a real person.
    submit_state: Mapped[str] = mapped_column(String(16), default="PENDING", nullable=False)

    # ── outcome ──────────────────────────────────────────────
    recording_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    duration_seconds: Mapped[float | None] = mapped_column(Float, nullable=True)
    user_speech_duration: Mapped[float | None] = mapped_column(Float, nullable=True)

    #: Exactly what Hunar returned, never edited. Kept beside the coerced
    #: values so the UI can show a recruiter the literal words behind any
    #: interpreted answer, and so a normaliser bug is recoverable.
    raw_result: Mapped[dict[str, Any] | None] = mapped_column(JSONVariant, nullable=True)
    normalized_result: Mapped[dict[str, Any] | None] = mapped_column(JSONVariant, nullable=True)

    # ── scoring ──────────────────────────────────────────────
    score: Mapped[float | None] = mapped_column(Float, nullable=True)
    score_breakdown: Mapped[dict[str, Any] | None] = mapped_column(JSONVariant, nullable=True)
    disqualified: Mapped[bool] = mapped_column(default=False, nullable=False)
    disqualified_reason: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ── retries and errors ───────────────────────────────────
    retry_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    max_retries: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    error_code: Mapped[str | None] = mapped_column(String(64), nullable=True)
    error_detail: Mapped[str | None] = mapped_column(Text, nullable=True)

    #: Drives lazy reconciliation: a non-terminal call untouched for a
    #: few seconds is refreshed from Hunar on the next read.
    last_synced_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # No ORM relationships back to the domain tables on purpose. This
    # module is shared, and pointing it at `hiring` would both invert the
    # dependency and make the sourcing app's arrival a rewrite rather than
    # an addition. Domains declare their own side, and queries that need a
    # candidate alongside a call join explicitly, which is what the results
    # view does anyway.


class WebhookEvent(UUIDMixin, Base):
    """Audit trail and idempotency ledger for inbound webhooks.

    Every delivery is persisted verbatim before it is interpreted, for two
    reasons. Hunar retries at one, two, four and eight minutes, so the same
    event arrives repeatedly and the unique ``dedupe_key`` collapses the
    duplicates. And the payload shape for these events is undocumented, so
    keeping the raw body is what makes an unexpected shape diagnosable
    rather than merely broken.
    """

    __tablename__ = "webhook_event"
    __table_args__ = (Index("ix_webhook_event_token", "callback_token", "event_type"),)

    #: sha256 of event type, token and raw body. Two deliveries of the same
    #: event collapse to one row.
    dedupe_key: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)

    event_type: Mapped[str] = mapped_column(String(48), nullable=False)
    callback_token: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    call_attempt_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("call_attempt.id", ondelete="CASCADE"), nullable=True, index=True
    )

    signature_valid: Mapped[bool] = mapped_column(default=False, nullable=False)
    hunar_timestamp: Mapped[int | None] = mapped_column(Integer, nullable=True)
    payload: Mapped[dict[str, Any] | None] = mapped_column(JSONVariant, nullable=True)

    received_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    processed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    process_error: Mapped[str | None] = mapped_column(Text, nullable=True)
