/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Healthz
     * @description Liveness. Answers if the process is running, nothing more.
     */
    get: operations["healthz_healthz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/readyz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readyz
     * @description Readiness. Actually touches the database and reports the voice mode.
     */
    get: operations["readyz_readyz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/meta": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Meta
     * @description Runtime facts the frontend needs, including whether data is simulated.
     */
    get: operations["meta_meta_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/hiring/jobs/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Preview Agent
     * @description Render the agent script and extraction schema for a draft role.
     */
    post: operations["preview_agent_api_v1_hiring_jobs_preview_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/hiring/jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Jobs */
    get: operations["list_jobs_api_v1_hiring_jobs_get"];
    put?: never;
    /** Create Job */
    post: operations["create_job_api_v1_hiring_jobs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/hiring/jobs/{job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Job */
    get: operations["get_job_api_v1_hiring_jobs__job_id__get"];
    put?: never;
    post?: never;
    /**
     * Archive Job
     * @description Archive rather than delete. Screening results describe real calls.
     */
    delete: operations["archive_job_api_v1_hiring_jobs__job_id__delete"];
    options?: never;
    head?: never;
    /** Update Job */
    patch: operations["update_job_api_v1_hiring_jobs__job_id__patch"];
    trace?: never;
  };
  "/api/v1/hiring/jobs/{job_id}/candidates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Candidates */
    get: operations["list_candidates_api_v1_hiring_jobs__job_id__candidates_get"];
    put?: never;
    /** Add Candidate */
    post: operations["add_candidate_api_v1_hiring_jobs__job_id__candidates_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/hiring/jobs/{job_id}/candidates/import": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Import Candidates
     * @description Import candidates from a CSV export.
     */
    post: operations["import_candidates_api_v1_hiring_jobs__job_id__candidates_import_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/hiring/jobs/{job_id}/candidates/{candidate_id}/decision": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Set Decision
     * @description Record a recruiter's shortlist or reject decision.
     *
     *     The score ranks; a person decides. This endpoint is what keeps the
     *     automated ranking advisory rather than determinative.
     */
    patch: operations["set_decision_api_v1_hiring_jobs__job_id__candidates__candidate_id__decision_patch"];
    trace?: never;
  };
  "/api/v1/hiring/jobs/{job_id}/candidates/{candidate_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Candidate */
    delete: operations["delete_candidate_api_v1_hiring_jobs__job_id__candidates__candidate_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/hiring/jobs/{job_id}/calls/launch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Launch
     * @description Place screening calls.
     *
     *     Creates the job's voice agent on first use. Candidates who already
     *     have a completed or in-flight call are skipped rather than dialled
     *     again, and anything the telephony layer refuses comes back with its
     *     reason attached rather than failing the whole batch.
     */
    post: operations["launch_api_v1_hiring_jobs__job_id__calls_launch_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/hiring/jobs/{job_id}/calls": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Calls
     * @description List call attempts, refreshing any that are still in flight.
     */
    get: operations["list_calls_api_v1_hiring_jobs__job_id__calls_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/hiring/jobs/{job_id}/calls/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh Calls
     * @description Force a refresh, ignoring the usual staleness interval.
     *
     *     Exists for the operator who is watching a call and wants an answer
     *     now rather than on the next poll.
     */
    post: operations["refresh_calls_api_v1_hiring_jobs__job_id__calls_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/hiring/jobs/{job_id}/results": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Results
     * @description Return the results table's columns and rows together.
     *
     *     Columns come from the job's stored field specification, so a single
     *     endpoint and a single frontend table render every role no matter what
     *     it asks. ``in_progress`` tells the client whether to keep polling.
     */
    get: operations["results_api_v1_hiring_jobs__job_id__results_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/webhooks/hunar/{callback_token}/{event_slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Receive
     * @description Authenticate one webhook delivery and schedule a state refresh.
     */
    post: operations["receive_webhooks_hunar__callback_token___event_slug__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AgentPreview
     * @description Exactly what the voice agent will be told, shown before any call.
     *
     *     This is the screen that makes the product legible: a recruiter can
     *     read the script and the extraction schema their job description
     *     produced, and correct it, rather than discovering a bad prompt from a
     *     confused candidate on the phone.
     */
    AgentPreview: {
      /** Introduction */
      introduction: string;
      /** Objective */
      objective: string;
      /** Agent Prompt */
      agent_prompt: string;
      /** Result Prompt */
      result_prompt: string;
      /** Result Schema */
      result_schema: {
        [key: string]: string;
      };
      /** Variables */
      variables: string[];
    };
    /**
     * AnswerType
     * @description How an answer is coerced, rendered and scored.
     *
     *     Hunar returns every value as a string, so this is our declaration of
     *     what the string is meant to represent. It drives the normaliser, the
     *     column renderer and the scoring rules from one place.
     * @enum {string}
     */
    AnswerType: "BOOLEAN" | "NUMBER" | "STRING" | "ENUM";
    /** Body_import_candidates_api_v1_hiring_jobs__job_id__candidates_import_post */
    Body_import_candidates_api_v1_hiring_jobs__job_id__candidates_import_post: {
      /** File */
      file: string;
    };
    /** CallAttemptOut */
    CallAttemptOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Candidate Id */
      candidate_id?: string | null;
      /** Hunar Call Id */
      hunar_call_id?: string | null;
      /** Status */
      status: string;
      /** Lifecycle Status */
      lifecycle_status: string;
      /** Engagement Status */
      engagement_status?: string | null;
      /** Answered By */
      answered_by?: string | null;
      /** Recording Url */
      recording_url?: string | null;
      /** Duration Seconds */
      duration_seconds?: number | null;
      /** Raw Result */
      raw_result?: {
        [key: string]: unknown;
      } | null;
      /** Normalized Result */
      normalized_result?: {
        [key: string]: unknown;
      } | null;
      /** Score */
      score?: number | null;
      /** Score Breakdown */
      score_breakdown?: {
        [key: string]: unknown;
      } | null;
      /**
       * Disqualified
       * @default false
       */
      disqualified: boolean;
      /** Disqualified Reason */
      disqualified_reason?: string | null;
      /** Error Code */
      error_code?: string | null;
      /** Error Detail */
      error_detail?: string | null;
      /**
       * Retry Count
       * @default 0
       */
      retry_count: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** CandidateCreate */
    CandidateCreate: {
      /** Name */
      name: string;
      /** Mobile Number */
      mobile_number: string;
      /** Extra */
      extra?: {
        [key: string]: string;
      };
    };
    /**
     * CandidateDecision
     * @enum {string}
     */
    CandidateDecision: "PENDING" | "SHORTLISTED" | "REJECTED";
    /**
     * CandidateImportReport
     * @description Outcome of a spreadsheet import.
     *
     *     Rejected rows are returned with their reason rather than silently
     *     dropped, because a recruiter who uploaded 200 rows and got 180
     *     candidates needs to know which twenty were lost and why.
     */
    CandidateImportReport: {
      /** Imported */
      imported: number;
      /** Skipped Duplicates */
      skipped_duplicates: number;
      /** Rejected */
      rejected?: {
        [key: string]: string;
      }[];
      /** Candidates */
      candidates?: components["schemas"]["CandidateOut"][];
    };
    /** CandidateOut */
    CandidateOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Mobile Number */
      mobile_number: string;
      /**
       * Mobile Masked
       * @default
       */
      mobile_masked: string;
      /** Source */
      source: string;
      decision: components["schemas"]["CandidateDecision"];
      /** Decision Note */
      decision_note?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** DecisionUpdate */
    DecisionUpdate: {
      decision: components["schemas"]["CandidateDecision"];
      /** Note */
      note?: string | null;
    };
    /** DependencyState */
    DependencyState: {
      /** Name */
      name: string;
      /** Ok */
      ok: boolean;
      /** Detail */
      detail?: string | null;
    };
    /**
     * FieldSpec
     * @description One column of the results table, derived from a question.
     *
     *     Returned alongside the rows so the frontend can build a table for a
     *     schema it has never seen. ``system`` marks the fields every job gets
     *     regardless of what the recruiter asked.
     */
    FieldSpec: {
      /** Key */
      key: string;
      /** Label */
      label: string;
      answer_type: components["schemas"]["AnswerType"];
      /** Enum Options */
      enum_options?: string[] | null;
      /**
       * Weight
       * @default 0
       */
      weight: number;
      /**
       * Is Knockout
       * @default false
       */
      is_knockout: boolean;
      /**
       * System
       * @default false
       */
      system: boolean;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: "ok";
      /** Version */
      version: string;
      /** Environment */
      environment: string;
    };
    /** JobCreate */
    JobCreate: {
      /** Title */
      title: string;
      /** Company Name */
      company_name: string;
      /** Location */
      location?: string | null;
      /**
       * Description Raw
       * @default
       */
      description_raw: string;
      /**
       * Language
       * @default ENGLISH
       */
      language: string;
      /**
       * Voice Persona
       * @default NEHA
       */
      voice_persona: string;
      /** Persona Name */
      persona_name?: string | null;
      /**
       * Timezone
       * @default Asia/Kolkata
       */
      timezone: string;
      /** Questions */
      questions: components["schemas"]["QuestionInput"][];
    };
    /** JobDetail */
    JobDetail: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Title */
      title: string;
      /** Company Name */
      company_name: string;
      /** Location */
      location?: string | null;
      /** Language */
      language: string;
      /** Voice Persona */
      voice_persona: string;
      status: components["schemas"]["JobStatus"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Candidate Count
       * @default 0
       */
      candidate_count: number;
      /**
       * Call Count
       * @default 0
       */
      call_count: number;
      /**
       * Completed Count
       * @default 0
       */
      completed_count: number;
      /**
       * Shortlisted Count
       * @default 0
       */
      shortlisted_count: number;
      /**
       * In Flight Count
       * @default 0
       */
      in_flight_count: number;
      /** Description Raw */
      description_raw: string;
      /** Persona Name */
      persona_name?: string | null;
      /** Timezone */
      timezone: string;
      /** Hunar Agent Id */
      hunar_agent_id?: string | null;
      /** Agent Synced At */
      agent_synced_at?: string | null;
      /** Questions */
      questions?: components["schemas"]["QuestionOut"][];
      /** Field Spec */
      field_spec?: components["schemas"]["FieldSpec"][];
      preview?: components["schemas"]["AgentPreview"] | null;
    };
    /**
     * JobStatus
     * @description Where a role is in its screening lifecycle.
     * @enum {string}
     */
    JobStatus: "DRAFT" | "READY" | "CALLING" | "DONE" | "ARCHIVED";
    /** JobSummary */
    JobSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Title */
      title: string;
      /** Company Name */
      company_name: string;
      /** Location */
      location?: string | null;
      /** Language */
      language: string;
      /** Voice Persona */
      voice_persona: string;
      status: components["schemas"]["JobStatus"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Candidate Count
       * @default 0
       */
      candidate_count: number;
      /**
       * Call Count
       * @default 0
       */
      call_count: number;
      /**
       * Completed Count
       * @default 0
       */
      completed_count: number;
      /**
       * Shortlisted Count
       * @default 0
       */
      shortlisted_count: number;
      /**
       * In Flight Count
       * @default 0
       */
      in_flight_count: number;
    };
    /** JobUpdate */
    JobUpdate: {
      /** Title */
      title?: string | null;
      /** Company Name */
      company_name?: string | null;
      /** Location */
      location?: string | null;
      /** Description Raw */
      description_raw?: string | null;
      /** Language */
      language?: string | null;
      /** Voice Persona */
      voice_persona?: string | null;
      /** Persona Name */
      persona_name?: string | null;
      /** Questions */
      questions?: components["schemas"]["QuestionInput"][] | null;
    };
    /** LaunchReport */
    LaunchReport: {
      /** Launched */
      launched: number;
      /** Skipped */
      skipped: number;
      /** Blocked */
      blocked?: {
        [key: string]: string;
      }[];
      /** Calls */
      calls?: components["schemas"]["CallAttemptOut"][];
    };
    /**
     * LaunchRequest
     * @description Ask to place calls for a set of candidates.
     */
    LaunchRequest: {
      /** Candidate Ids */
      candidate_ids?: string[] | null;
      /**
       * Max Retry Count
       * @default 0
       */
      max_retry_count: number;
      /**
       * Retry Interval Hours
       * @default 0
       * @enum {integer}
       */
      retry_interval_hours: 0 | 3 | 6 | 9 | 12 | 24;
    };
    /** MetaResponse */
    MetaResponse: {
      /** Version */
      version: string;
      /** Environment */
      environment: string;
      voice: components["schemas"]["VoiceModeState"];
      /** People Provider */
      people_provider: string;
      /** Calling Window */
      calling_window: string;
      /** Allowlist Size */
      allowlist_size: number;
    };
    /**
     * PreviewRequest
     * @description Ask what the agent would be told, without saving anything.
     *
     *     Powers the live preview in the create-job form. Making the generated
     *     script visible before any call is placed is what lets a recruiter
     *     catch a bad prompt themselves, rather than hearing about it from a
     *     confused candidate.
     */
    PreviewRequest: {
      /**
       * Title
       * @default the role
       */
      title: string;
      /**
       * Company Name
       * @default the company
       */
      company_name: string;
      /** Location */
      location?: string | null;
      /**
       * Description Raw
       * @default
       */
      description_raw: string;
      /**
       * Language
       * @default ENGLISH
       */
      language: string;
      /** Questions */
      questions: components["schemas"]["QuestionInput"][];
    };
    /**
     * QuestionInput
     * @description One question as the recruiter defines it.
     */
    QuestionInput: {
      /** Text */
      text: string;
      /** Label */
      label: string;
      /** @default STRING */
      answer_type: components["schemas"]["AnswerType"];
      /** Enum Options */
      enum_options?: string[] | null;
      /** Extraction Hint */
      extraction_hint?: string | null;
      /**
       * Weight
       * @default 1
       */
      weight: number;
      /**
       * Is Knockout
       * @default false
       */
      is_knockout: boolean;
      /** Scoring Rule */
      scoring_rule?: {
        [key: string]: unknown;
      } | null;
    };
    /** QuestionOut */
    QuestionOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Order Index */
      order_index: number;
      /** Text */
      text: string;
      /** Label */
      label: string;
      /** Field Key */
      field_key: string;
      answer_type: components["schemas"]["AnswerType"];
      /** Enum Options */
      enum_options?: string[] | null;
      /** Extraction Hint */
      extraction_hint?: string | null;
      /** Weight */
      weight: number;
      /** Is Knockout */
      is_knockout: boolean;
      /** Scoring Rule */
      scoring_rule?: {
        [key: string]: unknown;
      } | null;
    };
    /** ReadinessResponse */
    ReadinessResponse: {
      /** Ready */
      ready: boolean;
      /** Dependencies */
      dependencies: components["schemas"]["DependencyState"][];
    };
    /**
     * ResultRow
     * @description One candidate's screening outcome.
     */
    ResultRow: {
      /**
       * Candidate Id
       * Format: uuid
       */
      candidate_id: string;
      /** Candidate Name */
      candidate_name: string;
      /** Mobile Masked */
      mobile_masked: string;
      decision: components["schemas"]["CandidateDecision"];
      /** Call Id */
      call_id?: string | null;
      /** Status */
      status: string;
      /** Recording Url */
      recording_url?: string | null;
      /** Duration Seconds */
      duration_seconds?: number | null;
      /** Score */
      score?: number | null;
      /** Score Breakdown */
      score_breakdown?: {
        [key: string]: unknown;
      } | null;
      /**
       * Disqualified
       * @default false
       */
      disqualified: boolean;
      /** Disqualified Reason */
      disqualified_reason?: string | null;
      /** Values */
      values?: {
        [key: string]: unknown;
      };
      /** Raw Values */
      raw_values?: {
        [key: string]: unknown;
      };
    };
    /**
     * ResultsResponse
     * @description Columns and rows together, so the table can build itself.
     */
    ResultsResponse: {
      /** Columns */
      columns: components["schemas"]["FieldSpec"][];
      /** Rows */
      rows: components["schemas"]["ResultRow"][];
      /** Total */
      total: number;
      /** Completed */
      completed: number;
      /**
       * In Progress
       * @default false
       */
      in_progress: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /**
     * VoiceModeState
     * @description What the UI needs to describe the current data source truthfully.
     */
    VoiceModeState: {
      /**
       * Mode
       * @enum {string}
       */
      mode: "live" | "mock";
      /** Configured Mode */
      configured_mode: string;
      /** Degraded */
      degraded: boolean;
      /** Degrade Reason */
      degrade_reason?: string | null;
      /** Banner */
      banner?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  healthz_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  readyz_readyz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadinessResponse"];
        };
      };
    };
  };
  meta_meta_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MetaResponse"];
        };
      };
    };
  };
  preview_agent_api_v1_hiring_jobs_preview_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PreviewRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentPreview"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_jobs_api_v1_hiring_jobs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobSummary"][];
        };
      };
    };
  };
  create_job_api_v1_hiring_jobs_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JobCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_job_api_v1_hiring_jobs__job_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  archive_job_api_v1_hiring_jobs__job_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_job_api_v1_hiring_jobs__job_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JobUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_candidates_api_v1_hiring_jobs__job_id__candidates_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CandidateOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_candidate_api_v1_hiring_jobs__job_id__candidates_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CandidateCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CandidateOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  import_candidates_api_v1_hiring_jobs__job_id__candidates_import_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_import_candidates_api_v1_hiring_jobs__job_id__candidates_import_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CandidateImportReport"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  set_decision_api_v1_hiring_jobs__job_id__candidates__candidate_id__decision_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
        candidate_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DecisionUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CandidateOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_candidate_api_v1_hiring_jobs__job_id__candidates__candidate_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
        candidate_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  launch_api_v1_hiring_jobs__job_id__calls_launch_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LaunchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LaunchReport"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_calls_api_v1_hiring_jobs__job_id__calls_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CallAttemptOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  refresh_calls_api_v1_hiring_jobs__job_id__calls_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CallAttemptOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  results_api_v1_hiring_jobs__job_id__results_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResultsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  receive_webhooks_hunar__callback_token___event_slug__post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        callback_token: string;
        event_slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
